# Generated by Django 2.2.15 on 2020-08-20 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.BooleanField(default=True)),
                ('body', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
