# Generated by Django 2.2.15 on 2020-08-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghostpost',
            old_name='type_of',
            new_name='type_of_post',
        ),
    ]
