# Generated by Django 2.2.15 on 2020-08-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost', '0002_auto_20200820_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='down_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='up_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
