# Generated by Django 2.2.15 on 2020-08-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost', '0003_auto_20200820_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
