# Generated by Django 2.2.15 on 2020-08-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost', '0007_ghostpost_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='secret',
            field=models.CharField(max_length=7),
        ),
    ]
